config/routes.rb
Gallery2::Application.routes.draw do

  devise_for :customers, :path => "customer",
                         :path_names => { :sign_in => 'login',
                                          :sign_out => 'logout'}

  devise_for :users, :path => "/user",
                      :path_names => { :sign_in => 'login',
                                       :sign_out => 'logout',
                                       :password => 'secret',
                                       :confirmation => 'verification',
                                       :unlock => 'unblock',
                                       :registration => 'register',
                                       :sign_up => 'signup' }

  namespace :customer do
    resources :customers, only: [:show] do
      resources :albums, only: [:show] do
      end
    end
  end

resources :users, :except => [:index] do
  member do
    get :dashboard
  end
  resources :customers do
    resources :notes
    resources :albums do
      resources :photos, :only => [:index, :create, :destroy]
    end
  end
end

root :to => 'users#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  
  belongs_to :customer
  attr_accessible :text, :title, :customer_id

  def created_time
  	t = created_at
  	t.strftime("%H:%M %d-%m-%Y")
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json
  def index
    @user = current_user
    @customer = @user.customers.find(params[:customer_id])
    @notes = @customer.notes

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @user = current_user
    @customer = @user.customers.find(params[:customer_id])
    @note = @customer.notes.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @user = current_user
    @customer = @user.customers.find(params[:customer_id])
    @note = @customer.notes.build(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to user_customer_notes_path(@user, @customer) , notice: 'Note was successfully created.' }
        format.json do
          render json: {
            note: @note,
            status: :created,
            note_item: render_to_string(partial: 'note_item', locals: {note: @note}, formats: [:html])
          }.to_json
        end
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json do
        render json: {
          note: @note,
          status: :deleted
        }.to_json
      end
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for [@user, @customer, @note] do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/_note_item.html.erb
<li class="media" data-media-note-id="<%= note.id %>"> 
  <span class="pull-left">
    <span class="item-icon fontello-icon-pin-1"></span>
  </span>
  <div class="media-body"> 
    <span class="label label-success"><%= note.title %></span><br />
    <span class="date"><%=note.created_time%></span> 
    <span class="quick-menu-icon pull-right"> 
    <!--    <a class="edit fontello-icon-edit"></a> 
    <a class="state fontello-icon-archive"></a> -->

      <%= link_to "", user_customer_note_path(@user, @customer, note, :json),   "data-note-remove-btn-id " => note.id, :class => 'state fontello-icon-trash-1', :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Sind Sie sicher?'))%>
     </span>
     <p class="note"><%= note.text %></p>
  </div>
</li>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= note.title %></td>
    <td><%= note.text %></td>
    <td><%#= link_to 'Show', note %></td>
    <td><%#= link_to 'Edit', edit_note_path(note) %></td>
    <td><%#= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Note', new_user_customer_note_path(@user, @customer) %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @note.title %>
</p>

<p>
  <b>Text:</b>
  <%= @note.text %>
</p>