config/routes.rb
Gallery2::Application.routes.draw do

  devise_for :customers, :path => "customer",
                         :path_names => { :sign_in => 'login',
                                          :sign_out => 'logout'}

  devise_for :users, :path => "/user",
                      :path_names => { :sign_in => 'login',
                                       :sign_out => 'logout',
                                       :password => 'secret',
                                       :confirmation => 'verification',
                                       :unlock => 'unblock',
                                       :registration => 'register',
                                       :sign_up => 'signup' }

  namespace :customer do
    resources :customers, only: [:show] do
      resources :albums, only: [:show] do
      end
    end
  end

resources :users, :except => [:index] do
  member do
    get :dashboard
  end
  resources :customers do
    resources :notes
    resources :albums do
      resources :photos, :only => [:index, :create, :destroy]
    end
  end
end

root :to => 'users#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  attr_accessible :album_id, :image

  mount_uploader :image, ImageUploader

  include Rails.application.routes.url_helpers

  def to_jq_image
    {
      "name" => read_attribute(:image),
      "size" => image.size,
      "url" => image.url,
      "thumbnail_url" => image.thumb_small.url,
      "delete_url" => user_customer_album_photo_path(:user_id => album.customer.user_id, :customer_id => album.customer_id , :album_id => album_id, :id => id),
      "delete_type" => "DELETE"
    }
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @user = current_user
    @customer = @user.customers.find(params[:customer_id])
    @album = @customer.albums.find(params[:album_id])
    @photos = @album.photos
 #   @photo = @album.photos.build
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos.map{|photo| photo.to_jq_image } }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @user = current_user
    @customer = @user.customers.find(params[:customer_id])
    @album = @customer.albums.find(params[:album_id])
    @photo = @album.photos.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @user = current_user
    @customer = @user.customers.find(params[:customer_id])
    @album = @customer.albums.find(params[:album_id])
    @photo = @album.photos.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @user = current_user
    @customer = @user.customers.find(params[:customer_id])
    @album = @customer.albums.find(params[:album_id])
    @photo = @album.photos.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @user = current_user
    @customer = @user.customers.find(params[:customer_id])
    @album = @customer.albums.find(params[:album_id])
    @photo = @album.photos.build(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html {
          render :json => [@photo.to_jq_image].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => [@photo.to_jq_image].to_json
        }
      else
        render :json => [{:error => "custom_failure"}], :status => 304
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @user = current_user
    @customer = @user.customers.find(params[:customer_id])
    @album = @customer.albums.find(params[:album_id])
    @photo = @album.photos.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to user_customer_album_photos_url(@user, @customer, @album), notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @user = current_user
    @customer = @user.customers.find(params[:customer_id])
    @album = @customer.albums.find(params[:album_id])
    @photo = @album.photos.find(params[:id])
    @photo.destroy

    render :json => true
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for [@album, @photo], :html => {:multipart => true} do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :album_id %><br />
    <%= f.number_field :album_id %>
  </div>
  <div class="field">
    <%= image_tag(@photo.image.thumb.url) if @photo.image? %>
    <%= f.file_field :image,  multiple: true, name: "photo[image]" %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
 <td data-photo-id=<%= photo.id %> class="span2 well">
  asdsdfds
    <%= image_tag(photo.image.thumb.url) if photo.image? %>
    <td class="actions">
      <%= link_to 'Destroy', album_photo_path(@album, photo, :json), "data-photo-destroy-id" => photo.id %>
    </td>
 </td>

app/views/photos/create.js.erb
<% if @photo.new_record? %>
  alert("Failed to upload photo: <%#= j @photo.errors.full_messages.join(',').html %>");
<% else %>
	//alert('ok');
	$("#photos").append("<%= j render(@photo) %>");
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%#= link_to 'Show', @photo %> |
<%= link_to 'Back', album_photos_path(@album) %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<div id="photos" >
  <%= render @photos %>
</div>
<div class="clear"></div>


<%= form_for @album.photos.build, :url => { :action => "create" } do |f| %>
  <%#= f.label :photo %>
  <%= f.file_field :photo, multiple: true, name: "photo[image]" %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br />

<%= link_to 'New Photo', new_album_photo_path(@album) %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%#= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Album:</b>
  <%= @photo.album_id %>
</p>

<p>
  <b>Image:</b>
  <%= @photo.image %>
</p>


<%#= link_to 'Edit', edit_photo_path(@photo) %> |
<%#= link_to 'Back', photos_path %>