config/routes.rb
Gallery2::Application.routes.draw do

  devise_for :customers, :path => "customer",
                         :path_names => { :sign_in => 'login',
                                          :sign_out => 'logout'}

  devise_for :users, :path => "/user",
                      :path_names => { :sign_in => 'login',
                                       :sign_out => 'logout',
                                       :password => 'secret',
                                       :confirmation => 'verification',
                                       :unlock => 'unblock',
                                       :registration => 'register',
                                       :sign_up => 'signup' }

  namespace :customer do
    resources :customers, only: [:show] do
      resources :albums, only: [:show] do
      end
    end
  end

resources :users, :except => [:index] do
  member do
    get :dashboard
  end
  resources :customers do
    resources :notes
    resources :albums do
      resources :photos, :only => [:index, :create, :destroy]
    end
  end
end

root :to => 'users#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="sidebar-left panel-side">
<% if user_signed_in? %>
  <div class="page-container">
    <div id="header-container">
      <div id="header">
        <div class="navbar navbar-inverse navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container-fluid">
              <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span> <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="brand" href="javascript:void(0);">
                <img src="/assets/demo/logo-brand.png">
              </a>

              <!--
              <div class="search-global">
                <input id="globalSearch" class="search search-query input-medium" type="search">
                <a class="search-button" href="javascript:void(0);">
                  <i class="fontello-icon-search-5"></i>
                </a>
              </div>
            -->
              <div class="nav-collapse collapse">
                <ul class="nav user-menu visible-desktop">
                  <li>
                    <a class="btn-glyph fontello-icon-edit tip-bc" href="javascript:void(0);" title="Messages">
                      <span class="badge badge-important">8</span>
                    </a>
                  </li>
                  <li>
                    <a class="btn-glyph fontello-icon-mail-1 tip-bc" href="javascript:void(0);" title="Emails">
                    </a>
                  </li>
                  <li>
                    <a class="btn-glyph fontello-icon-lifebuoy tip-bc" href="javascript:void(0);" title="Support">
                      <span class="badge badge-important">4</span>
                    </a>
                  </li>
                </ul>
                <ul class="nav">
                  <li>
                    <a href="<%= dashboard_user_path(current_user) %>">Dashboard</a>
                  </li>
                  <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                      <span class="fontello-icon-list-1"></span>Kunden <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                        <a href="<%= user_customers_path(current_user) %>">Kundenliste</a>
                      </li>
                      <!--
                      <li>
                        <a href="component-widgets-remember.html">Remember</a>
                      </li>
                      <li>
                        <a href="component-widgets-users.html">User List</a>
                      </li>
                      <li class="divider"></li>
                      <li class="nav-header">Next Update</li>
                      <li>
                        <a href="javascript:void(0);">Contacts</a>
                      </li>
                      <li>
                        <a href="javascript:void(0);">Email</a>
                      </li>
                    -->
                    </ul>
                  </li>
                  <!--
                  <li>
                    <a href="component-fullcalendar-demo.html">
                      <span class="fontello-icon-calendar"></span>Calendar
                    </a>
                  </li>
                  <li>
                    <a href="javascript:void(0);">
                      <span class="fontello-icon-users"></span>Contacts
                    </a>
                  </li>
                  -->
                </ul>
              </div>
            </div>
          </div>
        </div>
        <!-- // navbar -->

        <div class="header-drawer">
            <div class="mobile-nav text-center visible-phone">
              <a href="javascript:void(0);" class="mobile-btn" data-toggle="collapse" data-target=".sidebar">
                <i class="aweso-icon-chevron-down"></i> Components
              </a>
            </div>
            <!-- // Resposive navigation -->
            <div class="breadcrumbs-nav hidden-phone">
              <ul id="breadcrumbs" class="breadcrumb">
                <li>
                  <a href="javascript:void(0);"><i class="fontello-icon-home f12"></i> Dashboard
                  </a>
                  <span class="divider">/</span>
                </li>
                <li class="dropdown">
                  <a href="javascript:void(0);">Table </a>
                  <span class="divider">/</span>
                  <ul class="dropdown-menu">
                    <li><a href="javascript:void(0);">Table</a></li>
                    <li><a href="javascript:void(0);">Elements</a></li>
                    <li><a href="javascript:void(0);">Elements</a></li>
                    <li><a href="javascript:void(0);">Elements</a></li>
                  </ul>
                </li>
                <li class="active">Boo Admin </li>
              </ul>
            </div>
            <!-- // breadcrumbs -->
        </div>
        <!-- // drawer -->
      </div>
    </div>
    <!-- // header-container -->
    <div id="main-container">
        <div id="main-sidebar" class="sidebar sidebar-inverse">
            <div class="sidebar-item">
                <div class="media profile">
                    <div class="media-thumb media-left thumb-bordereb"> <a class="img-shadow" href="javascript:void(0);"><img class="thumb" src="/assets/user/user_male.png"></a> </div>
                    <div class="media-body">
                        <h5 class="media-heading"><%= current_user.email %></h5>
                        <p class="data">Letzter Login: <%= current_user.current_sign_in_at %><br />
                        <%= link_to "Abmelden", destroy_user_session_path, method: :delete %> </p>
                    </div>
                </div>
            </div>
            <!-- // sidebar item - profile -->

            <ul id="mainSideMenu" class="nav nav-list nav-side">
                <li class="accordion-group">
                    <div class="accordion-heading"> <a href="<%= dashboard_user_path(current_user) %>" data-parent="#mainSideMenu" class="accordion-toggle"> <span class="item-icon fontello-icon-monitor"></span> <i class="chevron fontello-icon-right-open-3"></i> Dashboard </a> </div>

                </li>
                <!-- // item accordionMenu Dashboard -->
                <li class="accordion-group">
                    <div class="accordion-heading">
                      <a href="#accCustomer" data-parent="#mainSideMenu" data-toggle="collapse" class="accordion-toggle">
                        <span class="item-icon aweso-icon-list-alt"></span>
                        <i class="chevron fontello-icon-right-open-3"></i> Kunden
                      </a>
                    </div>
                    <ul class="accordion-content nav nav-list collapse" id="accCustomer">
                        <li>
                          <a href="<%= user_customers_path(current_user) %>">
                            <i class="fontello-icon-right-dir"></i> Kundenliste
                          </a>
                        </li>
                    </ul>
                </li>
                <!-- // item accordionMenu UI Elements -->
                <li class="accordion-group">
                    <div class="accordion-heading"> <a href="#accCalendar" data-parent="#mainSideMenu" data-toggle="collapse" class="accordion-toggle"> <span class="item-icon fontello-icon-calendar"></span> <i class="chevron fontello-icon-right-open-3"></i> Calendar </a> </div>
                    <ul class="accordion-content nav nav-list collapse" id="accCalendar">
                        <li> <a href="component-fullcalendar-demo.html"> <i class="fontello-icon-right-dir"></i> <span class="hidden-tablet">Calendar </span> Demo </a> </li>
                        <li> <a href="component-fullcalendar.html"> <i class="fontello-icon-right-dir"></i> <span class="hidden-tablet">Calendar </span> Style </a> </li>
                    </ul>
                </li>
                <!-- // item accordionMenu Calendar -->
            </ul>
            <!-- // sidebar menu -->

            <div class="sidebar-item"></div>
            <!-- // sidebar item -->

        </div>
        <!-- // sidebar -->
         <div id="main-content" class="main-content container-fluid">
          <%= yield %>
        </div>
        <!-- // main-content -->
      </div>
      <!-- // main-container  -->
  </div>
  <!-- // page-container  -->
<% elsif customer_signed_in? %>
  <div class="page-container">
    <div id="header-container">
      <div id="header">
        <div class="navbar navbar-inverse navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container-fluid">
              <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span> <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="brand" href="javascript:void(0);">
                <img src="/assets/demo/logo-brand.png">
              </a>
              <div class="nav-collapse collapse">
                <ul class="nav user-menu visible-desktop">
                  <li>
                    <a class="btn-glyph fontello-icon-edit tip-bc" href="javascript:void(0);" title="Messages">
                      <span class="badge badge-important">8</span>
                    </a>
                  </li>
                  <li>
                    <a class="btn-glyph fontello-icon-mail-1 tip-bc" href="javascript:void(0);" title="Emails">
                    </a>
                  </li>
                  <li>
                    <a class="btn-glyph fontello-icon-lifebuoy tip-bc" href="javascript:void(0);" title="Support">
                      <span class="badge badge-important">4</span>
                    </a>
                  </li>
                  <li> <%= link_to "Abmelden", destroy_customer_session_path, method: :delete %> </li>
                </ul>
                <ul class="nav">
                  <li>
                    <a href="<%#= dashboard_user_path(current_user) %>">Dashboard</a>
                  </li>
                   <!--
                  <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                      <span class="fontello-icon-list-1"></span>Kunden <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                        <a href="<%#= user_customers_path(current_user) %>">Kundenliste</a>
                      </li>

                      <li>
                        <a href="component-widgets-remember.html">Remember</a>
                      </li>
                      <li>
                        <a href="component-widgets-users.html">User List</a>
                      </li>
                      <li class="divider"></li>
                      <li class="nav-header">Next Update</li>
                      <li>
                        <a href="javascript:void(0);">Contacts</a>
                      </li>
                      <li>
                        <a href="javascript:void(0);">Email</a>
                      </li>

                    </ul>
                  </li>

                  <li>
                    <a href="component-fullcalendar-demo.html">
                      <span class="fontello-icon-calendar"></span>Calendar
                    </a>
                  </li>
                  <li>
                    <a href="javascript:void(0);">
                      <span class="fontello-icon-users"></span>Contacts
                    </a>
                  </li>
                  -->
                </ul>
              </div>
            </div>
          </div>
        </div>
        <!-- // navbar -->
      </div>
    </div>
    <!-- // header-container -->
    <div id="main-container">
      <div id="main-content" class="main-content container-fluid">
        <%= yield %>
      </div>
      <!-- // main-content -->
    </div>
      <!-- // main-container  -->
  </div>
  <!-- // page-container  -->
<% else %>
  <%= yield %>
<% end %>
</body>
</html>